### ISSUE TITLE
[ITERATION] Positionality Dimensions Definitions

### ISSUE THREAD

**Issue by celestemespinoza** [usds/equity_practice#12]
## Description
Natasha provided an initial menu for teams to select positionality dimensions. With multiple teams, we have seen the request for greater fidelity definitions for each dimension. 

### Acceptance Criteria
(see below for original list and link to planning canvas)

1. Each dimension should have well defined bounds for what is seen as core versus peripheral
2. Each dimension should have well crafted examples so participants know how to consistently plot
3. All dimensions should undergo at least one cycle of review asynchronously or via workshop

## Tasks

- [x] ** Include definitions for all dimensions**
- [x] ** Make sure all dimensions have examples, and revise, as necessary, examples in current list **
- [x] Make sure all updates are included in the planning canvas that we will be sending out to teams requesting positionality exercises
- [ ] Schedule time for review at upcoming DEIA Council meeting
- [x] Add to documentation for facilitation and guidance

## Project Artifacts
[Positionality Planning Canvas](https://usds.enterprise.slack.com/docs/TD42BGDLM/F061L4EHEAD) - A canvas that can be duplicated when working with a team to plan a positionality exercise; in the future, they could use this individually or with a facilitator plan a session

[Positionality Mural Exercise](https://app.mural.co/t/usdigitalservice0135/m/usdigitalservice0135/1688682093846/26b79b984266b12d80b730dabebe85a33b202fe1?sender=u13c8485b33f98e7ba1c50392)

### Current Dimensions in Mural Exercise
* Race/Ethnicity (Black, Latino, Native, Pacific Islander, Asian, Middle Eastern, White)
* Neurodiversity (Significant neurodivergence, some neurodivergence, no neurodivergence)
* Gender Identity (Trans/Intersex/Nonbinary, Cisgender Woman, Cisgender Man)
* Caregiver (adults, children, another caregiving responsibility, none)
* Housing (Unhoused/sheltered, renter, homeowner)
* Skin Color (dark, various shades, white)
* Class (Poor, Middle Class, Upper Class)
* Age (Young Middle Aged, Old or by generation)
* Transitions in Life Experiences (ex: finances, education, etc)
* Citizenship (Undocumented, asylum seeker, documented, US citizen)
* Formal Education (ex: Elementary, High School, Postsecondary)
* Upbringing (Poor, Middle Class, Upper Class)
* Language (English first language, Learned English, Little or no english)
* USDS Context (tech/non tech, govt experience, role, tenure, etc.)
* Employment (Unemployed, Hourly/Underemployed, Fully employed)
* Physical Ability (Significant disability, some disability, no disability)
* Sexual Orientation (Lesbian/Bisexual, Pansexual, Asexual, Gay Man, Heterosexual)
* Religion (Muslim, Hindu, Buddhist, Jewish, Christian)
* Career Experience (public sector → private sector)

**Comment by celestemespinoza** [comment]
@natasha-jamal Can we have Council review these at the next meeting to gather feedback and close out this ticket?

**Comment by celestemespinoza** [comment]
Will work with @natasha-jamal to figure out next scope of work on this. Would like to user test with Council.

**Comment by natasha-jamal** [comment]
let's discuss - I guess if there are any other things we want Council to look at soon - I would love to give them as a package and potentially use sync meeting time to work on this/or just have1-2 people review async? We could also potentially run positionality with Council in Jan?
