### ISSUE TITLE
Lead Capture for v0.5 Soft Launch

### ISSUE THREAD

**Issue by celestemespinoza** [usds/equity_practice#13]
## Description
We have put out a challenge to our project leads to consult at least once and use at least one tool by the end of January 2023. We will need to figure out how to capture and manage leads from generation through consultation.

### Acceptance Criteria
We have mechanisms to take in lead generation and also something in place for who will own managing this service point and how we will share it amongst our team.

- define what is most important to capture for each lead and make denote whether this happens on our end or theirs
- implement a central means of coordinating this data and capturing next steps, other notes for each consultation
- document our initial roll out of this process

## Tasks

- [ ] Find out how and if it's possible to move all intake from Polly to internal Microsoft Forms
- [ ] Determine what fields we need to capture for leads 
- [ ] Draft spreadsheet for capture
- [ ] Document a preliminary lead generation & nurture process

## Project Artifacts

**Comment by celestemespinoza** [comment]
@AlexBornkesselUSDS Feel free to begin refining this ticket!

**Comment by AlexBornkesselUSDS** [comment]
Sounds good! I'd like to propose integrating the items from the [IN PROGRESS Engagement Follow-ups](https://github.com/orgs/usds/projects/176/views/3?pane=issue&itemId=41417507) with this ticket - and then we'd delete the in-progress ticket. 

The engagement items should be in our lead capture spreadsheet. @celestemespinoza @jeremyzitomer-usds Would you agree?

**Comment by celestemespinoza** [comment]
![Image](https://github.com/usds/equity_practice/assets/74199261/f6b11e56-c595-42ba-a8c3-43ae0913c877)

**Comment by celestemespinoza** [comment]
Leads Caputure Mural

https://app.mural.co/t/usdigitalservice0135/m/usdigitalservice0135/1702423857243/208fced866a5fa04b63a671786f8e6ef95544423?sender=u13c8485b33f98e7ba1c50392

**Comment by AlexBornkesselUSDS** [comment]
@celestemespinoza This looks great! Are you wanting us to go through this during our adoption plan meeting? Or, what would be most helpful?

**Comment by AlexBornkesselUSDS** [comment]
@celestemespinoza I added in some stickies re: workflow, especially looking at:
- Service Type
- Triage Workflow

Overall, my main question is: How do we want to define "equity customer" - is that at an individual staff member level OR team-level? If there's a way for the form to serve both individuals and teams, that'd be butter. That said, if we want to focus in on customer = a USDS team and we start the equity-as-a-service model with our team's effort within that (eg. "equity consultations" and maybe "equity tools"), I can get behind that too. 

**re: Form Fields,** I added input re: lifecycle field and service of interest field. Will chime in more once you (or others) speak into the "equity customer" question.

**Comment by AlexBornkesselUSDS** [comment]
Given input from the A11y team and 
[@Natasha Jamal (she/her)](https://usds.slack.com/team/U03TKNXD8KF)
 note re: Mina's input, I updated this workflow to be "Project Support" and removed the call out to accessibility specifically.

A longer-term rec is that we align this with the Project Toolkit effort and work with the Product CoP leadership potentially, to lean into "this is how we deliver" vs. calling it out as an additive kind of thing. As of right now, there is now helpline so to speak if a project or staff member wants support except for a more DIY approach of pinging who you know, COP leadership or bringing something up in QPC.

**Link to form:** 
https://slack.com/shortcuts/Ft06ALL3RB8F/57188784182f3d6000aceefb5d43d608

**Comment by celestemespinoza** [comment]
Made edits to form per Mina. It sounds like we are going to do this via a shared email inbox.

**Comment by celestemespinoza** [comment]
We're going to be pushed into SalesForce which is good because SF but bad because timing. This effort is blocked or dead.
