### ISSUE TITLE
v0 Tools Success Metrics

### ISSUE THREAD

**Issue by celestemespinoza** [usds/equity_practice#17]
## Description
The success of any tool for delivery hinges on baselining and benchmarking consistently through each iteration and post implementation. For equity toolkit, we will need to measure both project success after the use of our tools and cultural change, e.g. the shift towards a culture of equity that is principal and woven throughout project work.

### Acceptance Criteria

1. Propose base metrics and process for measuring any tool based on project success
2. Propose base metrics and process for measuring any tool for cultural change
3. Base metrics should include what we do for teams with no baseline or approach to equity and what we do differently if the team has a baseline for equity
4. Propose how we capture individual and team maturity for approaching equity in general and with respect to delivery 

## Tasks

- [ ] Draft initial thought leadership for review by team for both sets of metrics @celeste
- [ ] Draft base metrics and/or process for project success
- [ ] Draft base metrics and/or process for measuring culture change towards maturity on equitable delivery

**Comment by AlexBornkesselUSDS** [comment]
@celestemespinoza The acceptance criteria for this one speak much more broadly than I understood this task originally. Suggest rescoping and scoping down. 

Proposed AC:
 - [ ] Identify no more than 3 quantitative metrics and corresponding questions to ask teams post tool usage
 - [ ] Determine timeline and process for answering quant questions
 - [ ] Develop and implement a metrics documentation process to capture and reference responses
