### ISSUE TITLE
Articulate what an equitable Project Lifecycle looks like

### ISSUE THREAD

**Issue by celestemespinoza** [usds/equity_practice#20]
## Description
Equity Delivery needs to understand the project lifecycle to uncover opportunities and areas of friction where equity could be better centered. This ticket aims to uncover the project lifecycle from submission to handoff, and includes selection, staffing, design, implementation, and measurement.

### Acceptance Criteria
The team has mapped out the existing lifecycle, identifying appropriate opportunities to incorporate or expand its current charge. The team has a draft and ideas of what an equity-delivery-centered project lifecycle might look like to review with leadership.

## Tasks

- [x] Draft current project lifecycle
- [ ] Validate current project lifecycle with leadership
- [ ] Validate current project lifecycle with projects leads
- [ ] Work on Project Selection portion of lifecycle for equity-delivery-centered project lifecycle

## Project Artifacts

[Mural board](https://app.mural.co/t/usdigitalservice0135/m/usdigitalservice0135/1696606513550/9ced603d4e5b2262b6032711bb558c743633f250?sender=u13c8485b33f98e7ba1c50392)

**Comment by AlexBornkesselUSDS** [comment]
@celestemespinoza I added a task re: syncing with the A11y team on the lifecycle and potential tools that align with it (from their POV). This is still in progress.
