### ISSUE TITLE
Presentation: Demo with US Digital Corps, Q&A Input

### ISSUE THREAD

**Issue by AlexBornkesselUSDS** [usds/equity_practice#22]
# Description
A fellow with the USDC suggested we should share our tools during one of their biweekly meetings. Per the fellow, USDC is also wanting to elevate equity in the full USDC experience and in its delivery work. Per fellow, a majority of USDC fellows are currently assigned to projects where they are working with USDS teams already.

Desired outcomes: 
 - Secure USDC input and sponsorship of the toolset, in prep for v1 launch
 - Use as a backdoor avenue to reach and secure adoption from USDSers via USDC, since they are currently working together on multiple projects  

# Consultation Notes
TBD. _Please be sure to include **date and time in bold** so we can capture notes across the evolution of the conversations if needed_

## Acceptance Criteria

1. Share about the tools
2. Invite fellows' input and feedback
3. Request USDC's sponsorship and support for v1 launch

## Tasks
TBD [INCLUDE THIS SECTION IF FACILITATION OPS REQUIRED, ADJUST AS NEEDED]
### Two weeks out

- [ ] Meet with project lead (or other designated party) to understand what the team wants to get out of the exercise at large (30 minutes - 2 weeks out)
- [ ] Send out a [Positionality Dimensions canvas](https://usds.enterprise.slack.com/docs/TD42BGDLM/F061L4EHEAD) for the project lead to fill out
- [ ] Work with project lead (or other designated party) to confirm 60 minutes for the exercise

### One week out

- [ ] Generate a worksheet with the submitted dimensions
- [ ] Generate a Mural board with submitted dimensions
- [ ] Send out [Exercise Invitation](https://usds.enterprise.slack.com/docs/TD42BGDLM/F062CQMCH88?focus_section_id=temp:C:cBIa826f5756ce64ea29ca859374) to the team (5 days advance)
-- Confirm agency emails and cc: OMB emails
-- Include Tookit folx as needed
- [ ] Confirm with team via Slack that no other concerns need to be addressed prior to exercise (2 days in advance)

### Day of

- [ ] Run exercise (day of)
- [ ] Export all conversation on Mural
-- Select the area for the conversation
--  Right-click to expose the menu
-- Select Download As
-- Select Selection, As PDF for each area
- [ ]  Send to Project Lead
- [ ] Delete all contents from the Mural board within 30 minutes, no later than 5P ET

### Week after

- [ ] Schedule Retro Call
- [ ] Gather Feedback
- [ ] Place all notes for iteration in a new ticket, as needed

## Project Artifacts
[ADD ARTIFACTS AS APPROPRIATE HERE]
[Positionality Dimensions menu](https://usds.enterprise.slack.com/docs/TD42BGDLM/F060XU6M0EB)
**_This should be updated with the menu + selections for each team_**

**Comment by AlexBornkesselUSDS** [comment]
@celestemespinoza @jeremyzitomer-usds Added. Would be good to talk about if / when we want to do this given breadth of work in progress.
