### ISSUE TITLE
Template Event / Facilitation / Consultation

### ISSUE THREAD

**Issue by AlexBornkesselUSDS** [usds/equity_practice#23]
# Description 

Speak to the tool(s) requested for use. Or, if this is a meeting, write the description with the desired outcome of the meeting or event.

# Acceptance Criteria

# Tasks
TBD [INCLUDE THIS SECTION IF FACILITATION OPS REQUIRED, ADJUST AS NEEDED]

## Two weeks out
- [ ] Meet with project lead (or other designated party) to understand what the team wants to get out of the exercise at large (30 minutes - 2 weeks out) 
- [ ] Send out a [Positionality Dimensions canvas](https://usds.enterprise.slack.com/docs/TD42BGDLM/F061L4EHEAD) for the project lead to fill out
- [ ] Work with project lead (or other designated party) to confirm 60 minutes for the exercise

## One week out
- [ ] Generate a worksheet with the submitted dimensions
- [ ] Generate a Mural board with submitted dimensions
- [ ] Send out [Exercise Invitation](https://usds.enterprise.slack.com/docs/TD42BGDLM/F062CQMCH88?focus_section_id=temp:C:cBIa826f5756ce64ea29ca859374) to the team (5 days advance)
- [ ] Confirm agency emails and cc: OMB emails
- [ ] Include Tookit folx as needed
- [ ] Confirm with team via Slack that no other concerns need to be addressed prior to exercise (2 days in advance)

## Day of
- [ ] Run exercise (day of)
- [ ] Export all conversation on Mural
-- Select the area for the conversation
-- Right-click to expose the menu
-- Select Download As
-- Select Selection, As PDF for each area
- [ ] Send to Project Lead
- [ ] Delete all contents from the Mural board within 30 minutes, no later than 5P ET

## Week after
- [ ] Schedule Retro Call
- [ ] Gather Feedback
- [ ] Place all notes for iteration in a new ticket, as needed

# Project Artifacts
[ADD ARTIFACTS AS APPROPRIATE HERE]

[Positionality Dimensions menu](https://usds.enterprise.slack.com/docs/TD42BGDLM/F060XU6M0EB)

This should be updated with the menu + selections for each team
