### ISSUE TITLE
Meeting: HRSA MCHB Equity Lead

### ISSUE THREAD

**Issue by AlexBornkesselUSDS** [usds/equity_practice#24]
# Description 

A HRSA agency partner on 0-5 offered to connect me with HRSA MCHB's Equity Lead. The desired outcome would be to learn more about her work and levers of influence so we can better understand the agency equity lead role. This can inform our tools and guidance for if/how USDS teams should engage an agency's equity lead in their project work. 

# Acceptance Criteria

# Tasks
TBD [INCLUDE THIS SECTION IF FACILITATION OPS REQUIRED, ADJUST AS NEEDED]

## Two weeks out
- [ ] Meet with project lead (or other designated party) to understand what the team wants to get out of the exercise at large (30 minutes - 2 weeks out) 
- [ ] Send out a [Positionality Dimensions canvas](https://usds.enterprise.slack.com/docs/TD42BGDLM/F061L4EHEAD) for the project lead to fill out
- [ ] Work with project lead (or other designated party) to confirm 60 minutes for the exercise

## One week out
- [ ] Generate a worksheet with the submitted dimensions
- [ ] Generate a Mural board with submitted dimensions
- [ ] Send out [Exercise Invitation](https://usds.enterprise.slack.com/docs/TD42BGDLM/F062CQMCH88?focus_section_id=temp:C:cBIa826f5756ce64ea29ca859374) to the team (5 days advance)
- [ ] Confirm agency emails and cc: OMB emails
- [ ] Include Tookit folx as needed
- [ ] Confirm with team via Slack that no other concerns need to be addressed prior to exercise (2 days in advance)

## Day of
- [ ] Run exercise (day of)
- [ ] Export all conversation on Mural
-- Select the area for the conversation
-- Right-click to expose the menu
-- Select Download As
-- Select Selection, As PDF for each area
- [ ] Send to Project Lead
- [ ] Delete all contents from the Mural board within 30 minutes, no later than 5P ET

## Week after
- [ ] Schedule Retro Call
- [ ] Gather Feedback
- [ ] Place all notes for iteration in a new ticket, as needed

# Project Artifacts
[ADD ARTIFACTS AS APPROPRIATE HERE]

[Positionality Dimensions menu](https://usds.enterprise.slack.com/docs/TD42BGDLM/F060XU6M0EB)

This should be updated with the menu + selections for each team

**Comment by AlexBornkesselUSDS** [comment]
@celestemespinoza @jeremyzitomer-usds FYI: I connected with Sam (HRSA) today on this, since we had a 1-1 re: 0-5 transitioning. She's made contact with HRSA's MCHB Equity Lead and is going to help bridge a convo re: 0-5, MCHB's equity work and our team's work. Sam will join us for the conversation. I sent some Jan time slots given current calendars and potential questions for discussion (see project artifacts).

**Comment by AlexBornkesselUSDS** [comment]
@natasha-jamal @jeremyzitomer-usds @celestemespinoza 
- This meeting was held yesterday. 
- I linked to the meeting notes and uploaded a copy of the Health Equity Toolkit HRSA MCHB has and will be using through its Equity Community of Practice. 
- I'm not sure how widely this resource can be shared, so **please keep internal to our team only for now**. 

Next steps: Share our tool suite and schedule a follow-up meeting to gain her input, feedback on our toolset.
