### ISSUE TITLE
Tool: Mindset Tool / Common Tenants of Equity

### ISSUE THREAD

**Issue by AlexBornkesselUSDS** [usds/equity_practice#25]
## Description
The 0-5 team used the table from Beyond Sticky Notes as a core way to align the team around shared values and mindsets. The team referenced this tool so many times. Had the team however kicked-off and oriented new team members to this tool earlier in the life experience process however, it would have saved a lot of time, energy and mitigated a lot of the conflict and helped reduce barriers to implementation from Day 1. 

### Acceptance Criteria
- [ ] Integrate a mindset tool into the Repo
- [ ]  
STRETHC GOAL: Make this a commnity-informed tool based on interviews and research. MVP though could be as simple as using the table from Beyond Sticky Notes. 

## Tasks
- [ ] Round out the table with some contextual information 
- [ ] Add the tool to the Repo

## Project Artifacts
![Image](https://github.com/usds/equity_practice/assets/114604977/55b6045b-f8fc-47c2-9ab0-78cc5ae2f7b1)
