### ISSUE TITLE
Meeting: A11y & Equity Team Sync - Tool Review & Refinement

### ISSUE THREAD

**Issue by AlexBornkesselUSDS** [usds/equity_practice#27]
# Description 

The A11y has reviewed the soft launch materials and requested a meeting with us so they can share ideas for tool refinement with accessibility in mind. This includes input on the facilitation guides for remote and virtual learning. The desired outcome is tangible paths forward to increase accessibility for soft launch materials, identifying what's possible before the v1 launch.

# Acceptance Criteria
 - [ ] Prioritization will be needed to identify what's in scope (and feasible) before the v1 launch compared to what are longer-range goals post v1 launch. 
 - [ ]  Update facilitation guides to incorporate some level of guidance for remote and/or virtual participation. 

# Tasks
- [ ] Send invite for meeting, with Zoom link and confirming meeting time works for all.
- [ ] Add next steps as tickets in the Project Board.

**Comment by AlexBornkesselUSDS** [comment]
@celestemespinoza @jeremyzitomer-usds I'd like to add any tickets that came from this meeting, to help close out this ticket. I need your help in refining the tickets, especially item #2:

1. Determine learning goals and questions for Tuscon design conversations (desired outcome is determining scope and prepping for Tuscon connection opp @celestemespinoza mentioned). 
3. Complete accessibility review and refinement of tool(s) for v1 (desired outcome would be addressing the 3 bullets Meg had in her outline in prep for v1 launch - understanding further testing would be post-launch).

**Comment by jeremyzitomer-usds** [comment]
@AlexBornkesselUSDS i think these AIs look good! Can you clarify what exactly you want input/tweaks on?

**Comment by AlexBornkesselUSDS** [comment]
Mainly, wasn't sure if I got item #2 fully. Like, if what I heard (as documented here), aligned with what you and @celestemespinoza heard/took away from the convo.
