### ISSUE TITLE
Meeting: A11y & Equity Team Sync - Delivery Lifecycle, Roadmap and Quality Criteria

### ISSUE THREAD

**Issue by AlexBornkesselUSDS** [usds/equity_practice#28]
# Description 

As a follow-up from the 12/8 meeting w/ the A11y team, we need to sync with them on the delivery process, 3-month project roadmap and quality criteria. Desired outcomes are 1) integrating a more comprehensive view of accessibility x equity moments and potential tools within the lifecycle and quality criteria, 2) expectation-setting on in-scope vs. out-of-scope for the equity team's 3-month roadmap and 3) greater team alignment in prep for meeting with Mina and USDS leadership to discuss USDS's equity definition and project scoping, determination process. 

# Acceptance Criteria
 - [ ] An updated delivery lifecycle with understood priority points. 
 - [ ] Include some initial ideas re: potential tools from the accessibility team that could be incorporated. Future conversations can further explore, determine what's in-scope for the v1 launch vs. out-of-scope.
 - [ ] Updated quality criteria that incorporates a greater accessibility POV. 
 - [ ] Shared understanding of the equity team's current 3-month roadmap and immediate next steps, especially re: prep for Mina and USDS leadership conversations around equity and the project determination process. 

# Tasks
- [ ] Send invite for meeting, with Zoom link and confirming meeting time works for all.
- [ ] Sharing current progress-to-date re: lifecycle and quality criteria w/ the A11y team.
- [ ] Setting up a shared MURAL space for us to work in.
- [ ] Add next steps as tickets in the Project Board.

**Comment by jeremyzitomer-usds** [comment]
Putting this here for posterity:
A few key talking points the Equity team will take into our consultations with various teams going forward:

- Equity includes accessibility
- Participatory engagement (at all project phases) should include communities/people with accessibility needs
- Even if agencies/teams are facing tradeoffs in terms of where to spend limited resources, they should do something to embed a11y, focused on what will maximize their impact given the constraints they’re under
- We should advertise the A11y team consistently during our consultations and facilitate a warm handoff to your team when appropriate and feasible

**Comment by jeremyzitomer-usds** [comment]
From Meg on 12/14:

Overall this hits on all of the right points! Here's something I got out of my head earlier today that might be helpful:
Equitable delivery prioritizes accessibility. If there’s a decision to reduce, exclude, or rush the effort that it takes to make something accessible for everyone, then we and our agency partners have to acknowledge and document the risk we're taking on. In this situation we can’t state that we’re practicing inclusivity or equitable delivery.
When we, USDS, prioritize accessibility and fail due to things that are truly out of our control, we must:
- document the risk and communicate it
- document the lessons learned
- as an organization, figure out how to improve the outcome in the future
We'll chat more in the coming weeks about how to define accessibility (encompasses many more people than those who use assistive technology), Louise and I are working on an explanation.

**Comment by AlexBornkesselUSDS** [comment]
@jeremyzitomer-usds @celestemespinoza I'd like to talk this through as a team at some point, using 0-5 Benefits Bundle as a use case example. Like, to share the decision points and trade-offs we weighed and as a peer review/retro, gain their team's input on what/how was done (or wasn't done). 

I worry about putting that 100% aim, all or nothing, on a team - and the effect that could have in teams saying 'yes/no' VERSUS being willing to find what they CAN move forward (now, next, later). I agree with the 100% target, yet sometimes staff are coming into situations where agencies _and their systems, structures_ aren't even at the crawl stage let along a 0. They are at negative 1000. And in those situations, there's still a lot of good accessibility work that can be done even if there's still room for much-needed progress.
