### ISSUE TITLE
[FFS INCOME VERIFICATION] Impact Scale Exercise

### ISSUE THREAD

**Issue by celestemespinoza** [usds/equity_practice#3]
### Description
FFS is in the process of discerning two intersecting but unique work streams that their work around income verification could take. They will be meeting on October 10, 2023 for an all-hands onsite to define proposed outcomes and tasks for this body of work.

Work stream 1: Improve the digital process for FFS income verification
Work stream 2: Assess, plan, and develop alternative modes of income verification for target users among the American public where a digital path is absent or difficult

### Acceptance Criteria

- Work with the FFS team to identify their goals for the onsite to determine which tools would serve them best
- Provide a proposed agenda and tool list for review
- Work with the FFS team to put together all necessary materials and artifacts, digital or otherwise, that will be necessary to run one or more exercises in person

### Tasks

- [x] Meet with FFS team to determine objectives for the onsite @Celeste
- [x] Propose tools that could be used to meet FFS objectives @Celeste
- [x] Propose an agenda to FFS @Celeste
- [x] Delineate prep for each exercise accepted by FFS for the onsite @Jeremy
- [x] Provide a list to FFS for any additional in-person materials that will be needed @Jeremy 
- [x] Edit Positionality Exercise worksheet @Celeste @Natasha @Jeremy
- [x] Print out copies of guides for each exercise @Jeremy
- [x] Confirm facilitators @Jeremy
- [x] Confirm location and time (prep to rolloff) @Jeremy
- [x] Confirm agenda for the exercises

### Artifacts
[Proposed Agenda](https://usds.enterprise.slack.com/docs/TD42BGDLM/F05V2J25BLL)

### Retro Notes
