### ISSUE TITLE
Consultation: SSA N8NN Discovery Sprint

### ISSUE THREAD

**Issue by jeremyzitomer-usds** [usds/equity_practice#30]
# Description 

Sprint-long equity consultation with USDS@SSA team, helping them to identify an Equity north star for their sprint and then create a plan to deliver on it

# Acceptance Criteria
- USDS@SSA team can define what delivering equity means in the context of their sprint
- USDS@SSA team has a reasonable plan to deliver equity, given the above definition
- USDS@SSA team demonstrates meaningful progress/commitment on delivering on the above plan

# Tasks

## Beforehand
- [x] Meet with USDS@SSA team to scope out and reach consensus on Equity team's contributions to sprint

## During
- [x] Identify what Equity exercises USDS@SSA team wants to use
- [x] Complete selected Equity exercises with USDS@SSA team
- [x] Bridge connection between USDS@SSA team and SSA Equity POCs
- [x] Define what equity delivery means in the context of sprint
- [x] Create plan to deliver equity given the definition above
- [x] Mobilize USDS@SSA team and SSA partners to execute equity delivery plan
- [x] Create intermediate progress readouts for sprint stakeholders
- [ ] Create final readout of equity deliverables for sprint stakeholders

## After
- [ ] Record lessons learned, tools used, value added, and ways of working during sprint

# Project Artifacts
[Results of "What's the Problem?" Exercise for SSA](https://usds.slack.com/archives/CNCDJBXD4/p1701877445499439?thread_ts=1701788467.420359&cid=CNCDJBXD4)

**Comment by jeremyzitomer-usds** [comment]
12/15 -- Noting a consultation victory!! Last night after corralling the USDS@SSA team toward a few sprint objectives for a few weeks, I helped the USDS@SSA team document likely demographic-based gaps in data integrity across the various datasets they’re analyzing for this sprint, and came out with [this analysis](https://app.mural.co/t/usdigitalservice0135/m/usdigitalservice0135/1694025253679/24841f7f167be1824aa1d79eb9721ed3efbe0d47?wid=0-1702569300403) which will shape how SSA analyzes their customers’ call intent going forward.
We demoed it today to our entire SSA stakeholder team and they were super engaged and appreciated it and asked a ton of interested questions. Our SSA Equity lead said this work made her feel “ecstatic”.

**Comment by jeremyzitomer-usds** [comment]
12/15 -- Will create a short #usds-victories writeup on the above win

**Comment by jeremyzitomer-usds** [comment]
12/15 -- Met with Owen and reached consensus that my time contributed to future sprints will be lower, on the order of 2 hrs/week. Going to downgrade this to 1 point for next sprint.

**Comment by jeremyzitomer-usds** [comment]
Now that we’ve [documented the demographic data integrity gaps](https://app.mural.co/t/usdigitalservice0135/m/usdigitalservice0135/1694025253679/24841f7f167be1824aa1d79eb9721ed3efbe0d47?wid=0-1702569300403), next steps are: a) draft a little #victories post for y’all to review, and b) in the next sprint, establish a plan with the SSA team for how they’ll address those data integrity gaps when they’re subsequently running their data analysis (things like oversampling underrepresented populations, normalizing for expected bias, etc)

**Comment by jeremyzitomer-usds** [comment]
@natasha-jamal reiterating from Slack, would you feel comfortable spending an hour or so reviewing the table in the Mural link above and flagging if there are any significant "compromises" to data integrity that those preconditions would suggest, that I haven't already noted down? Hoping to leverage a bit of your survey design/data collection expertise from the Gallup days! If so, feel free to assign yourself to this ticket too.

**Comment by natasha-jamal** [comment]
sure thing! and when do you need it by? (figuring out if I can do this once back on Jan 3 or if you need before then)

**Comment by jeremyzitomer-usds** [comment]
If you can do it by EOW the first week of January, that'd be great! Is that doable?

**Comment by celestemespinoza** [comment]
Given what's listed as deliverable for this, where are we at with this project? Are we attending check-ins as the sprint closes and we...

- [ ]  Create final readout of equity deliverables for sprint stakeholders
- [ ]  Create tickets for USDS support (e.g. data science support on data integrity gap analysis)

**Comment by jeremyzitomer-usds** [comment]
Update: been using this Mural board to capture "definition of equity" in an SSA context -- this is even something that (far down the road) could become a new tool to help teams define equity success metrics: https://app.mural.co/t/usdigitalservice0135/m/usdigitalservice0135/1706026824633/236e7a813f443c33af9188163915d3cec209a306?sender=u251162188f56721a08512222
