### ISSUE TITLE
Generate comms deliverable list

### ISSUE THREAD

**Issue by AlexBornkesselUSDS** [usds/equity_practice#33]
**Description**
Generate a comms strategy to help bring visibility to the equity work being done at USDS and beyond. 

**Acceptance Criteria**
- Should be multi-pronged, meaning brings visibility to more than a single audience, on a single platform or channel  
- Needs to be raise the visibility of equity work in and by communities, not just USDS's efforts
- Should include speaking opportunities, in addition to written-communications

**Tasks**

- [ ] Generate an initial idea list (see [Canvas](https://usds.enterprise.slack.com/docs/TD42BGDLM/F061Z8GJSG3))
- [ ] Review and identify priority ideas to pursue
- [ ] Establish a regular check-in cadence with USDS Comms to keep items moving
- [ ] Identify a task plan, with responsible parties and next steps
- [ ] Share highlights Mina during 11/7 check-in
