### ISSUE TITLE
Consultation: DOJ NLEAD

### ISSUE THREAD

**Issue by jeremyzitomer-usds** [usds/equity_practice#34]
# Description 

Ongoing equity consultation with USDS@DOJ team, helping them to identify an Equity north star for DOJ NLEAD project and then create a plan to deliver on it

# Acceptance Criteria
- USDS@DOJ team can define what delivering equity means in the context of their workstream
- USDS@DOJ team has a reasonable plan to deliver equity, given the above definition
- USDS@DOJ team demonstrates meaningful progress/commitment on delivering on the above plan

# Tasks

## Beforehand
- [x] Meet with USDS@DOJ team to scope out and reach consensus on Equity team's contributions to DOJ NLEAD workstream

## During
- [x] Define what equity delivery means in the context of DOJ workstream
- [x] Create plan to deliver equity given the definition of equity delivery above
- [x] Identify what Equity exercises USDS@DOJ team wants to use
- [ ] Complete selected Equity exercises with USDS@DOJ team
- [ ] Bridge connection between USDS@DOJ team and DOJ Equity POCs
- [ ] Mobilize USDS@DOJ team and DOJ partners to execute equity delivery plan

## After
- [ ] Record lessons learned, tools used, value added, and ways of working during workstream

# Project Artifacts
[Rough Equity support plan for DOJ NLEAD](https://usds.enterprise.slack.com/docs/TD42BGDLM/F068JP40J1H)

**Comment by jeremyzitomer-usds** [comment]
USDS@DOJ team interested in Participation Spectrum, Equity Support plan is based around that tool

**Comment by jeremyzitomer-usds** [comment]
As of 12/12, planning to bridge Kim Lopez @ DOJ (equity lead) with Karin and team

**Comment by jeremyzitomer-usds** [comment]
Next steps from 12/4: Karin to reach out to two DOJ stakeholders for 30-min prep call WITH those stakeholders before EOY
    * Karin will schedule a follow-up, will schedule a little time with us beforehand to prep us
    * Would like to get more detail on the actual workshop details leading up to the event itself

**Comment by meganp-usds** [comment]
Hey Jeremy! A few weeks ago we provided the DOJ NLEAD advice on accessibility practices. How can we ensure accessibility is incorporated into these efforts with the same team?

**Comment by jeremyzitomer-usds** [comment]
Hey Meg, let's have the Equity team and A11Y team meet for 15 mins to sync on goals of Equity team’s DOJ consultation, vis a vis goals of A11Y’s support of DOJ, and then figure out an action plan from there! I'll schedule a mtg.

**Comment by jeremyzitomer-usds** [comment]
Related: Had a meet and greet with Access to Justice office at DOJ today, Slack notes [here](https://usds.slack.com/archives/C06ALLZ1MD5/p1703089766557229).

Next step for Equity team: set up 60-min show-and-tell with USDS Equity team and DOJ ATJ for end of January

12/20-- sent email to DOJ ATJ team to set up time

**Comment by celestemespinoza** [comment]
@jeremyzitomer-usds With Karin moving over to DOJ, what outstanding work needs to happen with/out Karin's assistance?

**Comment by jeremyzitomer-usds** [comment]
Sent Karin a DM to talk equity exit strategy

**Comment by celestemespinoza** [comment]
Final session will be scheduled for week of March 4.

**Comment by jeremyzitomer-usds** [comment]
DOJ Handoff presentation includes a hefty shoutout to stakeholder engagement and the Participation Spectrum -- see their PPT attached

[USDS_DOJ NLEAD Handoff Document_DRAFT 3.5.2024.pptx](https://github.com/usds/equity_practice/files/14512194/USDS_DOJ.NLEAD.Handoff.Document_DRAFT.3.5.2024.pptx)
