### ISSUE TITLE
Consultation: Product CoP Adoption Strategy

### ISSUE THREAD

**Issue by jeremyzitomer-usds** [usds/equity_practice#36]
# Description 

Equity consultation with Product CoP leadership team, helping them to identify high-value opportunities for encouraging adoption of Equity tools and then creating a plan to deliver on it

# Acceptance Criteria
- Product CoP Leadership (PCL) team can define clear goals in terms of embedding equity across their CoP 
- PCL team has developed plan to encourage adoption of Equity Toolkit exercises
- PCL team has enacted plan, observed meaningful uptake, and can articulate value-add of Equity Toolkit exercises to their CoP

# Tasks

## Beforehand
- [x] Meet with PCL team to establish interest in Equity Toolkit artifacts and consultations

## During
- [ ] Scope out and reach consensus on Equity team's contributions to PCL's workstreams
- [ ] Define clear goals for equity delivery in the context of PCL's workstreams
- [ ] Deep-dive on Equity Toolkit exercises with PCL team
- [ ] Identify what Equity exercises PCL team wants to evangelize further with CoP
- [ ] Create plan to deliver equity/encourage tool adoption, given the goals for equity delivery above, including demoing the selected exercises
- [ ] Mobilize PCL team to execute above plan

## After
- [ ] Record lessons learned, tools used, value added, and ways of working during workstream

# Project Artifacts
[Link to 12/12 PCL meeting takeaways](https://usds.slack.com/archives/C06AG8RGTLY/p1702402998326999)

**Comment by jeremyzitomer-usds** [comment]
Created this Mural today to talk about Equity problem framing: https://app.mural.co/t/usdigitalservice0135/m/usdigitalservice0135/1704472062870/3cd69b7cf85a8bb475d4a6811edf75240ce76aa3?sender=u251162188f56721a08512222

Goal for next session: Get them to clearly elucidate 1-3 problem(s) they want to prioritize for equity in the Product CoP, and commit to 1-2 actions per problem to address those problems

**Comment by AlexBornkesselUSDS** [comment]
Updated ticket to include Product Jam task and slide deck. fyi @celestemespinoza @natasha-jamal @jeremyzitomer-usds

**Comment by AlexBornkesselUSDS** [comment]
Uploading the final deck! I'll screen share the deck and @celestemespinoza the Metrimeter. @natasha-jamal will introduce the team and I'll do the intro. @jeremyzitomer-usds will facilitate discussion and @celestemespinoza will bring us home. 

[Equity Delivery_Product Jam_Jan 2024_Final.pptx](https://github.com/usds/equity_practice/files/14088596/Equity.Delivery_Product.Jam_Jan.2024_Final.pptx)

**Comment by AlexBornkesselUSDS** [comment]
Also,I added the final deck to the ticket under project artifacts.

**Comment by jeremyzitomer-usds** [comment]
Note: setting biweekly cadence for meetings with Will going forward, short-term priorities is evangelizing our tools and getting Product CoP feedback on Project Toolkit/content module work

**Comment by celestemespinoza** [comment]
- Meeting set biweekly
- Product preview of Root for March 12*
- Will create another ticket for coordinated touchpoint across other CoPs,
