### ISSUE TITLE
Add equity-focused USDS Engineering interview question

### ISSUE THREAD

**Issue by jeremyzitomer-usds** [usds/equity_practice#37]
## Description
Work with Alex Kharbush and Kelvin to ensure sensitivity to equity/impact-related outcomes is reflected in new engineering interview process

### Acceptance Criteria
- Engineering competencies include sensitivity to equity/impact implications of decision-making
- Question is added to USDS engineering interview question bank, reflecting the above competency

## Tasks
- [ ] Propose draft question
- [ ] Propose draft evaluation criteria
- [ ] Propose draft engineering competency description
- [ ] Finalize the above

## Project Artifacts

**Comment by jeremyzitomer-usds** [comment]
message from Jeremy to Alex Kharbush as of 12/11:

> Here’s a draft question! Let me know what addl content you need from me to supplement this (sample answers, eval criteria, etc).
> You are beginning a new project with an agency stakeholder, focused on reducing homelessness. At the very first meeting, the stakeholder proposes a solution: your team should build an iOS app to allow people to apply for housing subsidies. What questions would you recommend your team ask, and why? For this question, focus on the content of what you would like your team to ask, not the tone, phrasing, or delivery of the questions.

**Comment by jeremyzitomer-usds** [comment]
Sent to Alex K, now waiting on feedback/next steps from Eng CoP leadership
