### ISSUE TITLE
Consultation: CDC-Prime HIV Surveillance

### ISSUE THREAD

**Issue by celestemespinoza** [usds/equity_practice#38]
# Description 

CDC-PRIME lead leanna-usds flagged a potential use case for Participation Spectrum with her team via Slack. We proactively reached out via Slack to schedule some time with her and team to discuss their needs and how we might best serve them as a customer.

We have recommended a 30 minute consultation to determine their needs and support for use of Participation Spectrum.

# Tasks

- [x] Reach out to team
- [ ] Schedule time with team for consultation
- [ ] Determine scope of work, as needed, moving forward

**Comment by celestemespinoza** [comment]
**Context**

![Image](https://github.com/usds/equity_practice/assets/74199261/4f54d1e3-b9c7-4b8d-82e5-31d74afefbec)


![Image](https://github.com/usds/equity_practice/assets/74199261/c749ba16-1a4d-47ce-acc3-b9a415d92148)

**Comment by celestemespinoza** [comment]
Did not respond. Moving to done.
