### ISSUE TITLE
Meeting: Follow-up with Victor re, Tools

### ISSUE THREAD

**Issue by AlexBornkesselUSDS** [usds/equity_practice#40]
# Description
We shared with the CDC Team the suite of equity tools. We've also been continuing our collab with Victor and a next step was to share the tools, work with him and hear his perspective, input and feedback. Desired outcome includes capturing input for synthesis with the collective feedback to help identify and prioritize next steps re: tool refinement and adoption. 

## Acceptance Criteria

1. Share about the tools
2. Invite POV, input and feedback
3. Invite and identify 1-2 priority items as a result of discussion

## Tasks
 - [ ] Schedule meeting
 - [ ] Prep deck / approach
 - [ ] Add POV, input, feedback into single-source-of-reference re: input-to-date
 - [ ] Add any new tickets to Git as a result

**Comment by AlexBornkesselUSDS** [comment]
@celestemespinoza @jeremyzitomer-usds Given schedules, we'll get this on the books for top of January. Moving to Sprint B.

**Comment by AlexBornkesselUSDS** [comment]
Sent new dates for weeks of Jan 8 and 15

**Comment by AlexBornkesselUSDS** [comment]
Followed up via Slack, offering times for 1/16. Also sent him a copy of our tools, so we can gain his input and feedback too. Reminder: CoP kick-off is scheduled for Jan. 17.

**Comment by celestemespinoza** [comment]
Victor provided feedback on the entire toolkit on 1/16/24. This might not be necessary anymore.

**Comment by jeremyzitomer-usds** [comment]
@AlexBornkesselUSDS can we consider this ticket done?
