### ISSUE TITLE
Updated Tool Deck for Jan Consultations

### ISSUE THREAD

**Issue by AlexBornkesselUSDS** [usds/equity_practice#41]
## Description
Start from the deck used for the CDC consultation on 12/13 and update it for upcoming consultations.

### Acceptance Criteria
 - [ ] ~~Equity definition & how USDS measures it~~
 - [ ] ~~Contextualize/anchor tools in guiding principles (bridge problem statement & intro of tools)~~
 - [x] Shorten: focus on the problem the tool helps solve, when to use it(?), cut quotes
 - [x] Plan for 20 minutes, hope for 15 and cut the difference for 17 min
 - [x] Enable time for Q&A
 - [x] Be prepared for in-depth questions re: tools
 - [x] Identify format: MURAL and/or PPT?   
 
## Tasks
- [x] Provide reco re: format, @AlexBornkesselUSDS 

## Project Artifacts
CDC Deck
Polly Link: https://web.polly.ai/3d8eoo
Slack Form Link: https://slack.com/shortcuts/Ft06ALL3RB8F/57188784182f3d6000aceefb5d43d608

## Notes
Have in prep for Product CoP and Design CoP meetings

**Comment by jeremyzitomer-usds** [comment]
12/13 presentation: 
https://app.mural.co/t/usdigitalservice0135/m/usdigitalservice0135/1702482053616/34d407441438535335a0bb19bd3d2bee98972293?sender=u251162188f56721a08512222

**Comment by celestemespinoza** [comment]
- Move into Powerpoint versus Mural
- Include flagship tools page to bring questions during the session?

**Comment by celestemespinoza** [comment]
@AlexBornkesselUSDS -- Jeremy is going to do some revisions this afternoon on this for DSAC tomorrow.

**Comment by jeremyzitomer-usds** [comment]
@AlexBornkesselUSDS this is a notification test

**Comment by jeremyzitomer-usds** [comment]
this is a tagless test

**Comment by jeremyzitomer-usds** [comment]
Made some edits to PPT for presentation tomorrow!
summary of edits:
- defined equity
- whittled down the "4 questions"
- combined slides 8-9
- appendicized the last 4 slides

[Equity.Delivery.Pitch.Deck_Dec.2023-JZ-edits.pptx](https://github.com/usds/equity_practice/files/13834949/Equity.Delivery.Pitch.Deck_Dec.2023-JZ-edits.pptx)

**Comment by AlexBornkesselUSDS** [comment]
Updated w/ Polly link & Git Repo visual, removed CoP mention (for now)

[Equity.Delivery.Pitch.Deck_Jan 2024.pptx](https://github.com/usds/equity_practice/files/13837685/Equity.Delivery.Pitch.Deck_Jan.2024.pptx)

**Comment by AlexBornkesselUSDS** [comment]
Also, added the polly and slack form links to ticket description

**Comment by celestemespinoza** [comment]
There were two pieces of acceptance criteria that we did not cover in the current iteration of the deck.

- [ ]  Equity definition & how USDS measures it
- [ ]  Contextualize/anchor tools in guiding principles (bridge problem statement & intro of tools)

But Im actually good with where our deck is because of how folks are responding to it. @AlexBornkesselUSDS @jeremyzitomer-usds are we good with closing out this ticket?

**Comment by AlexBornkesselUSDS** [comment]
I agree @celestemespinoza

**Comment by celestemespinoza** [comment]
Struck through items for documentation of current status. Closing ticket.

**Comment by AlexBornkesselUSDS** [comment]
To help with follow-ups, I created a PDF version that includes links to the facilitation guides and MURAL templates. 

[Equity.Delivery_PDF_Jan.2024.pdf](https://github.com/usds/equity_practice/files/13891128/Equity.Delivery_PDF_Jan.2024.pdf)
