### ISSUE TITLE
Meeting: OMB/HHS Tribal Convening

### ISSUE THREAD

**Issue by AlexBornkesselUSDS** [usds/equity_practice#45]
# Description 

The 0-5 Team convened with OMB and HHS Tribal leads to discuss ways to bring greater visibility to 0-5 efforts within Indian Country to further explore expansion / scaling considerations and opportunities. The 0-5 team invited the Equity team to join given the Equity team's work and attendance at NCAI.

# Acceptance Criteria
 - [ ] Gain learnings for how a current USDS project interacts with OMB/HHS Tribal leads and related needs, opportunities

# Tasks
- [X] Participate in meeting
- [ ] Add additional tickets to capture resulting action items.

**Comment by celestemespinoza** [comment]
**Notes**

- We proposed a planning meeting with Ryan.
- Integrate with 0-5 work? We need to figure that out. DC folks wouldn't require travel.
- Healthy Start budget might be zeroed out - working to budget for this program to continue at least until the end of 2024
- "Can't go through maternal health without [other] [mental health] [substance abuse] services"
- Tribal folks are in the driver seat: "here are the seven different questions to ask for input?"

AI:

- [ ] Coordinate with 0-5 team about what a presence at the convening could look like, NCAI's objective
- [ ] What are tribal priorities?
- [ ] Participation spectrum within a breakout session

**Comment by celestemespinoza** [comment]
0-5 will be on site visits. Closing this ticket out.
