### ISSUE TITLE
[CONSULTATION] Streamlining Immigration

### ISSUE THREAD

**Issue by celestemespinoza** [usds/equity_practice#48]
# Description 

On 12.18.23, Streamlining Immigration reached out to discuss how to incorporate equity into their current workstream. Meeting occurred on 12.20.23 at 1pm.

## From #incoming-channel
:bulb:Project Context:
More than 2 million cases are pending in U.S. immigration courts. This backlog has more than tripled in the past 7 years. The backlog causes delays and poses challenges for noncitizens—including children and families— who may wait for years to have their cases heard.  These delays postpone decisions for vulnerable populations who may be eligible for protections, such as asylum, but also prolongs the removal of those who do not have valid claims to remain. Furthermore, these delays result in increased work for 650+ immigration judges across the U.S., and the court staff.

:hammer_and_wrench: Current Problems:
In phase 1 of this project, from February to October 2023, USDSers worked in collaboration with the Department of Homeland Security (DHS) and DOJ’s Executive Office of Immigration Review (EOIR) to streamline systems for Asylum and Notice to Appear (NTA).  During phase 2, in November 2023, the USDS team conducted a discovery sprint focused on noncitizen case flow processes and backlog.  Emerging from that recent discovery sprint, this project is now entering phase 3, tentatively projected to run through June 2024 before entering additional phases.  As such the project’s name has changed from "Asylum/NTA" to "Streamlining Immigration Backlog" with exactly that focus:  to improve the noncitizen experience and expedite backlog.

This new project is focused on noncitizens who are eligible for enrollment in the Caseflow Management system— which has several pre-requisites— that the noncitizen have legal representation, not be in detention, not be a juvenile, and be deemed mentally well.  With these qualifying factors, the Caseflow Management system should theoretically enroll approximately +500k noncitizens in U.S. immigration courts in this year, but Caseflow Management enrollment is actually closer to 269K cases due to the massive overload and strain on the system.  USDS has found many opportunities to automate this Caseflow Management enrollment in a way that decreases limbo duration for the noncitizen and opens up more slots for other master calendar or merits hearings, thereby improving the overall throughput of immigration cases.  While this project is focused on that population of people who qualify for Caseflow Management, we expect there to be efficiencies and opportunities to improve the system for the larger noncitizen population as well.

## Notes from initial intake

- typically noncitizens will have to come to court; they get mailed and via email
- through this expedited process, the letter that they get in the mail might be out of date
- ** scared, people are nervous and confused; we don't want to lose the human touch (noncitizens)
- ** reduce burden for noncitizen, and clerk staff; allows other people to get processed faster

**competing goals:**

- core goal is around streamlining mainly manual processes for adjudications support staff with a benefit served to noncitizens, but in speeding things up there may be issues with trust and safety for noncitizens
- noncitizens are limited in their rights and representation in this area, and also limited in fully understanding the intricacies of the legal system in how it benefits them and also how it may not support them
- attorneys are the primary point of contact with clerk staff; noncitizens trust them to help them navigate the system and make sense of competing communications ("I have a letter that says show up to a hearing, but I just got an email that don't show up, how do I do the correct next step?")

**What the SI universe looks like:**

- clerk staff - we engage very close with the DoJ clerk staff, iterative user testing and feedback with them
- judges - engage with judges ad-hoc, as needed; their staff are primary users
- noncitizens - served by the management system by directly and by proxy of their attorneys
- attorneys - we can request to talk to attorneys; we have to call our own pro bono attorneys that we know
- DHS - prosecutorial side (DHS legal team) - we barely touch DHS

**Conversation/Brainstorming:**

- I asked the degree to which they were currently engaged with AILA (American Immigration Law Association) or similar organizations; they do not have that relationship yet with AILA or other CBOs at regional or national levels
- Nagela noted that the team wasn't sure if they were good candidates to utilize toolkit, and I said that they might consider grounding on the reach they could realistically give to people who represent noncitizens and noncitizens themselves, separate from the outcomes of case management
- I also noted that they could think about what strategy they want to employ in terms of engagement and research via Participation Spectrum and craft a more nuanced approach that could include a broader spectrum of voices that include AILA, Community Centers, and other Institutions that are the backbone to the process

## Next Steps

- [ ] Schedule time the afternoon of Friday January 5
- [ ] Include in invitation: Nagela Nukuna, Ellen Tinklein, John (Juan Jimenez), Sean Robertson, Kiley Dowling, Brian Estes
- [ ] They will bring: a more refined definition of what they feel their equity goal is for the target audience of attorneys as proxy to noncitizens
- [ ] We will: demo and q/a how reach/burden and participation spectrum could work to get them to some tactical next steps, and hopefully a strategy for the next wave of engagement and research

# Acceptance Criteria

# Tasks
TBD [INCLUDE THIS SECTION IF FACILITATION OPS REQUIRED, ADJUST AS NEEDED]

## Two weeks out
- [ ] Meet with project lead (or other designated party) to understand what the team wants to get out of the exercise at large (30 minutes - 2 weeks out) 
- [ ] Send out a [Positionality Dimensions canvas](https://usds.enterprise.slack.com/docs/TD42BGDLM/F061L4EHEAD) for the project lead to fill out
- [ ] Work with project lead (or other designated party) to confirm 60 minutes for the exercise

## One week out
- [ ] Generate a worksheet with the submitted dimensions
- [ ] Generate a Mural board with submitted dimensions
- [ ] Send out [Exercise Invitation](https://usds.enterprise.slack.com/docs/TD42BGDLM/F062CQMCH88?focus_section_id=temp:C:cBIa826f5756ce64ea29ca859374) to the team (5 days advance)
- [ ] Confirm agency emails and cc: OMB emails
- [ ] Include Tookit folx as needed
- [ ] Confirm with team via Slack that no other concerns need to be addressed prior to exercise (2 days in advance)

## Day of
- [ ] Run exercise (day of)
- [ ] Export all conversation on Mural
-- Select the area for the conversation
-- Right-click to expose the menu
-- Select Download As
-- Select Selection, As PDF for each area
- [ ] Send to Project Lead
- [ ] Delete all contents from the Mural board within 30 minutes, no later than 5P ET

## Week after
- [ ] Schedule Retro Call
- [ ] Gather Feedback
- [ ] Place all notes for iteration in a new ticket, as needed

# Project Artifacts
[ADD ARTIFACTS AS APPROPRIATE HERE]

This should be updated with the menu + selections for each team

**Comment by celestemespinoza** [comment]
@natasha-jamal FYSA
@jeremyzitomer-usds @AlexBornkesselUSDS Copy of notes from DM for visibility

**Comment by jeremyzitomer-usds** [comment]
this is a test of tagging @celestemespinoza

**Comment by jeremyzitomer-usds** [comment]
this is a test of not tagging celeste
