### ISSUE TITLE
Meeting: Fonda, Natasha re: CBO collab / "research panel", engagement center

### ISSUE THREAD

**Issue by AlexBornkesselUSDS** [usds/equity_practice#49]
# Description
Natasha and Fonda shared updates on their proposal in progress, Desired outcomes include 1) equity team gaining an understanding of the current proposal, 2) the related constraints and opps within it, and 3) how/where/when it ties into our team's work (or not).

Tangentially related: Potential to generate MOUs w/ orgs that bake in integrity of participation to help fast-track equitable participation between USDS teams and external community members. For the MOU item, we'd also want to talk w/ Maya Mechenbier to understand historical efforts and context broadly re: MOUs and USDS. 

## Acceptance Criteria
- [ ] Natasha/Fonda shares current proposal on the docket
- [ ] Natasha/Fonda speak to constraints and opps within it
- [ ] Identify how this does (or doesn't) related to the equity-team's work, including its coordination w/ external entities

## Tasks
 - [ ] Schedule meeting
 - [ ] Add any new tickets to Git as a result

**Comment by AlexBornkesselUSDS** [comment]
Started this ticket - @celestemespinoza @natasha-jamal 

@natasha-jamal Is this something you could coordinate? It could be as easy(?) as inviting Fonda to one of our team's current meetings in the New Year.

**Comment by natasha-jamal** [comment]
sure. I think the new design delivery lead might be helpful to include so I think @celestemespinoza was trying to aim for late Jan, but do we want earlier and I can just ask Fonda if she wants to bring them or just come herself?
