### ISSUE TITLE
Brown Bag: DSAC@CMS Participation Spectrum

### ISSUE THREAD

**Issue by jeremyzitomer-usds** [usds/equity_practice#51]
# Description 

Brown bag for DSAC@CMS on Participation Spectrum, bridged via Remy Decausemaker (Open Source lead @ DSAC@CMS)

# Acceptance Criteria
- Presentation given to DSAC@CMS on Participation Spectrum that conveys its value and how to use it
- We have a way to capture interest/uptake on P.S. from DSAC

# Tasks

## Beforehand
- [ ] Prep presentation
- [ ] Make sure Participation Spectrum is external-ready
- [ ] Ensure lead-tracking is prepared for presentation

## During
- [ ] Give presentation

## After
- [ ] Identify follow-up engagements, new POCs, ways to collaborate

# Project Artifacts
N/A

**Comment by jeremyzitomer-usds** [comment]
Scheduled for 1/5 at 10 am @celestemespinoza @AlexBornkesselUSDS

**Comment by jeremyzitomer-usds** [comment]
We can expect to present for 20-30 mins, with the remaining time for questions. Full brown bag learning session is 55 mins long.

**Comment by celestemespinoza** [comment]
Scheduled and conducted on 01/05/21
