### ISSUE TITLE
Create proposal for OMB CX Equity Team

### ISSUE THREAD

**Issue by AlexBornkesselUSDS** [usds/equity_practice#54]
## Description
During the OMB CX Equity syncs, USDS shared how it would like to help equip teams as they kick-off to have a broader set of equity-related tools, frameworks and language to use throughout the life of the project. 

### Acceptance Criteria
 - [ ] Speaks to a process that is usable by CX LX proejcts
 - [ ] Speaks to a process that is usable for OMB's HISP teams
 
## Tasks
- [ ] Seed idea for team's proposal during 1/19 sync
- [ ] Draft proposal
- [ ] Share proposal

## Project Artifacts
