### ISSUE TITLE
Consultation: Disaster

### ISSUE THREAD

**Issue by jeremyzitomer-usds** [usds/equity_practice#57]
# Description 

Ongoing equity consultation with Disaster team, helping them to identify what "equity due diligence" means for Disaster project and then create a plan to deliver on it

# Acceptance Criteria
- Disaster team can define their own equity problem/goals in the context of their workstream
- EqDel team can define what our capacity/resources are to support Disaster team's goals
- Disaster team has a reasonable plan to deliver equity, given the above goals
- Disaster team demonstrates meaningful progress/commitment on delivering on the above plan

# Tasks

## Beforehand
- [ ] Meet with Disaster team to scope out and reach consensus on Disaster team's equity "problem"
- [ ] Meet with Disaster team to scope out and reach consensus on Disaster team's equity goals
- [ ] EqDel team can define what resources/exercises are relevant to Disaster team and identify our capacity to support

## During
- [ ] Define what equity delivery means in the context of Disaster's goals
- [ ] Create plan to deliver equity given the goals of equity delivery above
- [ ] Assist Disaster team in completing selected Equity exercises
- [ ] Bridge connection between Disaster team and Equity/Tribal POCs
- [ ] Mobilize Disaster team and partners to execute equity delivery plan

## After
- [ ] Record lessons learned, tools used, value added, and ways of working during workstream

# Project Artifacts

**Comment by jeremyzitomer-usds** [comment]
We met with Charlie, we're going to meet with Dafina next to discuss equity project goals and how to integrate Equity tools

**Comment by jeremyzitomer-usds** [comment]
Cele made a BIG MISTAKE okay

**Comment by celestemespinoza** [comment]
Notes from 2.5.24

“Equity is something we’ve always considered but never made it explicit”

jeremy // they them
  [38 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707147339844599?thread_ts=1707147312.618019&cid=C0599G43LUA)
“We don’t know what we need to consider”


jeremy // they them
  [38 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707147348215289?thread_ts=1707147312.618019&cid=C0599G43LUA)
Sam used to be an equity advocate on this work


jeremy // they them
  [37 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707147384490899?thread_ts=1707147312.618019&cid=C0599G43LUA)
Previous pain points: requiring people fax supplementary materials in their applications


jeremy // they them
  [37 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707147402356649?thread_ts=1707147312.618019&cid=C0599G43LUA)
“The data shows that some of these hurdles cause worse outcomes for people”


jeremy // they them
  [37 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707147414194329?thread_ts=1707147312.618019&cid=C0599G43LUA)
FEMA has agreed that application and business rules need to change


jeremy // they them
  [36 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707147424411759?thread_ts=1707147312.618019&cid=C0599G43LUA)
“We have WH backing”


jeremy // they them
  [36 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707147442972409?thread_ts=1707147312.618019&cid=C0599G43LUA)
Okay so basically they have no idea what they’re doing with equity lol 
[@Celeste Espinoza](https://usds.slack.com/team/U01E4RE0754)
 
[@Alex Bornkessel](https://usds.slack.com/team/U044L6PFRJ4)
  (edited) 


jeremy // they them
  [36 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707147478277009?thread_ts=1707147312.618019&cid=C0599G43LUA)
CE: is there an initial focus for disaster recovery? Or is it all a single app? Answer: a single app


jeremy // they them
  [35 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707147491598919?thread_ts=1707147312.618019&cid=C0599G43LUA)
“We have data that higher income people have better outcomes”


Alex Bornkessel
  [35 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707147513797169?thread_ts=1707147312.618019&cid=C0599G43LUA)
they sound like they are in a solution/delivery space vs. a generative space


jeremy // they them
  [35 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707147518210739?thread_ts=1707147312.618019&cid=C0599G43LUA)
“Type of disaster greatly impacts the outcome. A big fire like Hawaii is much more total destruction and much harder to recover from”


Alex Bornkessel
  [35 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707147538608709?thread_ts=1707147312.618019&cid=C0599G43LUA)
(but yet haven't talked with any people, disaster survivors) (edited) 


jeremy // they them
  [34 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707147546575309?thread_ts=1707147312.618019&cid=C0599G43LUA)
Hmm good note 
[@Alex Bornkessel](https://usds.slack.com/team/U044L6PFRJ4)


jeremy // they them
  [34 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707147568004009?thread_ts=1707147312.618019&cid=C0599G43LUA)
Programs for specific disasters don’t account for variations in disasters


jeremy // they them
  [33 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707147655643649?thread_ts=1707147312.618019&cid=C0599G43LUA)
“A key outcome is how long does it take them to start rebuilding their lives”


jeremy // they them
  [31 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707147753380119?thread_ts=1707147312.618019&cid=C0599G43LUA)
“People don’t know if they need temporary evacuation housing AND have mold damage in the same FEMA consultation, but if they don’t have that data right then and there, they need to fax it”


Alex Bornkessel
  [30 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707147829246359?thread_ts=1707147312.618019&cid=C0599G43LUA)
good Q 
[@jeremy // they them](https://usds.slack.com/team/U01H7B8AZSA)
 - that was one of my questions too!


Alex Bornkessel
  [29 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707147880244619?thread_ts=1707147312.618019&cid=C0599G43LUA)
"doing some delivery work right now" (edited) 


jeremy // they them
  [29 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707147890644819?thread_ts=1707147312.618019&cid=C0599G43LUA)
(I asked it because you raised the point 
[@Alex Bornkessel](https://usds.slack.com/team/U044L6PFRJ4)
 ! lol)
:sweat_smile:
1



jeremy // they them
  [28 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707147940914759?thread_ts=1707147312.618019&cid=C0599G43LUA)
“Some implementation already exists, we’re working on other improvements with FEMA teams. We’re also doing other research/prototyping to identify what success means” (edited) 


Alex Bornkessel
  [28 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707147960996889?thread_ts=1707147312.618019&cid=C0599G43LUA)
what kind of research - given there's a prototype involved. This is where shared language and understanding of "a" lifecycle framework, would be so helpful.
:heavy_plus_sign:
1



jeremy // they them
  [27 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707147965663379?thread_ts=1707147312.618019&cid=C0599G43LUA)
Reaaallllly interesting glimpse of how projects work


Alex Bornkessel
  [25 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707148130236299?thread_ts=1707147312.618019&cid=C0599G43LUA)
That's really helpful to know, thanks 
[@Celeste Espinoza](https://usds.slack.com/team/U01E4RE0754)
!


jeremy // they them
  [24 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707148168628799?thread_ts=1707147312.618019&cid=C0599G43LUA)
“assistance we’re focusing on is individuals — can be unhoused, renters, or homeowners — it is for assistance to families/households, not farms, communities, utilities, etc”


jeremy // they them
  [24 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707148186649929?thread_ts=1707147312.618019&cid=C0599G43LUA)
ie, some design/solution elements have already been decided upon before deciding what success looks like here


jeremy // they them
  [22 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707148265628379?thread_ts=1707147312.618019&cid=C0599G43LUA)
CE: are we testing with each of the three “types” of individuals above separately? or doing a wholesale approach?
Katrina: Charlie did some initial quick work on this, saw some staff trainings of trauma-informed toolkit


jeremy // they them
  [22 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707148290087769?thread_ts=1707147312.618019&cid=C0599G43LUA)
“Folks being asked about the totality of their experience when they do not know the totality of their experience seems to be a big problem”


jeremy // they them
  [22 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707148319467749?thread_ts=1707147312.618019&cid=C0599G43LUA)
“How many appeals do they have to file, calls do they have to make to follow up?” etc


jeremy // they them
  [21 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707148345421209?thread_ts=1707147312.618019&cid=C0599G43LUA)
“Business rules behind the application also need to change”


Celeste Espinoza
  [21 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707148351032789?thread_ts=1707147312.618019&cid=C0599G43LUA)
Let's move forward: I feel like they could use participation spectrum for planning out and thinking about those segments with more granularity


Alex Bornkessel
  [21 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707148354316989?thread_ts=1707147312.618019&cid=C0599G43LUA)
"the business rules need to change bc it's the business rules that are defining the experience"


jeremy // they them
  [21 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707148357458499?thread_ts=1707147312.618019&cid=C0599G43LUA)
agreed 
[@Celeste Espinoza](https://usds.slack.com/team/U01E4RE0754)


jeremy // they them
  [21 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707148371404549?thread_ts=1707147312.618019&cid=C0599G43LUA)
and “What’s the Problem?” as a precursor


Alex Bornkessel
  [20 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707148403499899?thread_ts=1707147312.618019&cid=C0599G43LUA)
if we had a mindsets tool, would say that could be helpful too - could point them to the Philly mindset assessment tool (edited) 
:exclamation:
1



jeremy // they them
  [20 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707148407570289?thread_ts=1707147312.618019&cid=C0599G43LUA)
bc i don’t want them to just make a form prettier/accessible for longer that many people cannot access in the first place


Alex Bornkessel
  [19 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707148458502669?thread_ts=1707147312.618019&cid=C0599G43LUA)
goal of a mindset tool would give them language to surface equity more throughout the project, in an intentional and said way (vs. it remaining unsaid).


jeremy // they them
  [19 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707148466469839?thread_ts=1707147312.618019&cid=C0599G43LUA)
noting more interest in PS from Katrina, maybe less in Positionality


Celeste Espinoza
  [17 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707148562618039?thread_ts=1707147312.618019&cid=C0599G43LUA)
good call on mindset* 
[@Alex Bornkessel](https://usds.slack.com/team/U044L6PFRJ4)

if we could do a streamlined version of RBS - this team could utilize that as a grounding tool
:plusone:
1



jeremy // they them
  [15 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707148711972779?thread_ts=1707147312.618019&cid=C0599G43LUA)
yeah, maybe! it might be interesting to see if this team can go from a “service” problem to a “foundations” or “defaults” problem


jeremy // they them
  [13 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707148789594889?thread_ts=1707147312.618019&cid=C0599G43LUA)
“i would want any of these exercises to be done with all of us having equal footing with each other — ie team lead vis a vis ICs; not team lead bringing this in as a mandate for the group” (edited) 


Alex Bornkessel
  [11 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707148938111859?thread_ts=1707147312.618019&cid=C0599G43LUA)
i have to jump for a 0-5 call


Alex Bornkessel
  [11 minutes ago](https://usds.slack.com/archives/C0599G43LUA/p1707148958941609?thread_ts=1707147312.618019&cid=C0599G43LUA)
also, I'd be happy to take on the follow-up w/ this one

**Comment by celestemespinoza** [comment]
**Follow Up**

- [ ] Schedule Positionality for team for week of February 19
- [ ] Begin preparing additional tools for review: Participation Spectrum, Mindsets/RBS

Katrina send over the full set of team members so we can begin looking at schedules
@AlexBornkesselUSDS will run lead on dimensions and scheduling with this team
