### ISSUE TITLE
Consultation: Homelessness

### ISSUE THREAD

**Issue by jeremyzitomer-usds** [usds/equity_practice#58]
# Description 

Ongoing equity consultation with Homelessness team, helping them to identify what "equity/Tribal due diligence" means for Homelessness project and then create a plan to deliver on it

# Acceptance Criteria
- Homelessness team can define their own equity problem/goals in the context of their workstream
- EqDel team can define what our capacity/resources are to support Homelessness team's goals
- Homelessness team has a reasonable plan to deliver equity, given the above goals
- Homelessness team demonstrates meaningful progress/commitment on delivering on the above plan

# Tasks

## Beforehand
- [ ] Meet with Homelessness team to scope out and reach consensus on Homelessness team's equity "problem"
- [ ] Meet with Homelessness team to scope out and reach consensus on Homelessness team's equity goals
- [ ] EqDel team can define what resources/exercises are relevant to Homelessness team and identify our capacity to support

## During
- [ ] Define what equity delivery means in the context of Homelessness's goals
- [ ] Create plan to deliver equity given the goals of equity delivery above
- [ ] Assist Homelessness team in completing selected Equity exercises
- [ ] Bridge connection between Homelessness team and Equity/Tribal POCs
- [ ] Mobilize Homelessness team and partners to execute equity delivery plan

## After
- [ ] Record lessons learned, tools used, value added, and ways of working during workstream

# Project Artifacts

**Comment by celestemespinoza** [comment]
We met with Homelessness to primarily discuss Tribal. We facilitated a connection to Neill Manish. They have elected to pause.
