### ISSUE TITLE
Consultation: Passport Renewal

### ISSUE THREAD

**Issue by AlexBornkesselUSDS** [usds/equity_practice#59]
# Description 

Ongoing equity consultation with the Passport Renewal Team. 

- from Kelly: "We are grappling with how to run our next "Confidence Test" to include a wider audience than our first one that only included "friends and family". That user group was generally educated, english-speaking, and tech-literate.

# Acceptance Criteria
- Passport Renewal team can define their own equity problem/goals in the context of their workstream
- EqDel team can define what our capacity/resources are to support Homelessness team's goals
- Passport Renewal team has a reasonable plan to deliver equity, given the above goals
- Passport Renewal team demonstrates meaningful progress/commitment on delivering on the above plan

# Tasks

## Beforehand
- [ ] Meet with Passport Renewal team to scope out and reach consensus on Passport Renewal team's equity "problem"
- [ ] Meet with Passport Renewal team to scope out and reach consensus on Passport Renewal team's equity goals
- [ ] EqDel team can define what resources/exercises are relevant to Passport Renewal team and identify our capacity to support

## During
- [ ] Define what equity delivery means in the context of Passport Renewal's goals
- [ ] Create plan to deliver equity given the goals of equity delivery above
- [ ] Assist Passport Renewal team in completing selected Equity exercises
- [ ] Bridge connection between Passport Renewal team 
- [ ] Mobilize Passport Renewal team and partners to execute equity delivery plan

## After
- [ ] Record lessons learned, tools used, value added, and ways of working during workstream

# Project Artifacts

- [Feb QPC Project Backgrounder](https://github.com/usds/state/blob/master/projects/online-passport-renewals/OPR2.0-Launch/Quarterly%20Checkins/2024-02-12.md)
- [User Recruitment Goals.pptx](https://github.com/usds/equity_practice/files/14195181/User.Recruitment.Goals.pptx)

**Comment by AlexBornkesselUSDS** [comment]
@celestemespinoza Added this ticket and the PPT deck Dafina shared with us this AM. 

A note on the deck: It does lean more demographic-heavy re: customer segmentation. I like to press in there and expand thinking beyond demographics. I've found [the table in this resource](https://www.griffith.edu.au/griffith-business-school/social-marketing-griffith/resources/segmentation) as a quick way to achieve that (and the tool overall is a solid primer).

**Comment by celestemespinoza** [comment]
We provided lightweight segmentation recommendations for the project. We also reached out to Kelly about a follow up but have not heard back.

**Comment by celestemespinoza** [comment]
Advised with passport team on UX metrics, segmentation.
