### ISSUE TITLE
[PLAIN LANGUAGE] Positionality Radar

### ISSUE THREAD

**Issue by celestemespinoza** [usds/equity_practice#8]
## Description
Positionality refers to the social and political context that creates our identities in terms of race, class, gender, sexuality, ability status and more. It also describes how our identity influences, and potentially biases, our understanding of and outlook on the world. 

The Positionality Radar is a tool designed to facilitate USDS teams achieving a richer sense of self, of team and of the people involved in their projects. It is used to prompt meaningful conversations both in-the-moment and as teams pursue their project work.

The Equity Delivery team needs to ensure that the guides are plain language and accessible for both internal and external audiences to accommodate use in for USDS teams and in conjunction with agency partners. 

**This effort is time-sensitive. Soft launch for this tool is Monday, December 4.**

### Acceptance Criteria

- Current discussion guide should be reviewed for plain language, with recommendations/line edits provided to bring the guide to a wider audience
- Current template should should be reviewed for plain language, with recommendations/line edits provided to bring the guide to a wider audience
- Any outputs should include formatting to meet minimal accessibility compliance in Slack and Github

_The initial design of the tool and the guide have been evaluated by USDS teams. This is working on content that has been through a few iterations._

## Tasks

- [ ] Complete plain language review of Positionality Guide and provide recommendations/edits as comments in Slack canvas
- [ ] Complete plain language review of Positionality Dimensions and provide recommendations/edits as comments in Slack canvas
- [ ] Complete plain language review of Positionality Radar and provide edits in documentation of choice
- [ ] Assess content for accessibility compliance and provide feedback via Word document, e.g. headers, formatting, etc
- [ ] STRETCH GOAL: User evaluation with at least 5 USDSers

## Project Artifacts

![Positionality Radar Example](https://github.com/usds/equity_practice/assets/74199261/4f91f0ee-6f0a-4b73-8cb9-4541f666580c)

[Positionality, An End to End Guide](https://usds.enterprise.slack.com/docs/TD42BGDLM/F062CQMCH88)

[Positionality Dimensions](https://usds.enterprise.slack.com/docs/TD42BGDLM/F061L4EHEAD)

**Comment by meganp-usds** [comment]
@celestemespinoza Is there any opportunity to get feedback from future users of the tool? (agency and internal USDS) It would be really helpful to understand terms people don't understand, formatting that isn't clear, instructions that cause confusion, etc. That would help a lot in proposing edits to add clarity.

**Comment by celestemespinoza** [comment]
@meganp-usds 
Prior to the soft launch, we evaluated through facilitated exercise all three exercises with USDS Project Teams. We iterated on the protocol, facilitation delivery, and instruments for the exercises based on this feedback.

For the next phase of the launch, we are not planning on launch or visibility to agency partners. Agency partners will only have access to tools via a USDS team. We are also anticipating the vast majority of teams to still request facilitation. 

Can you recommend a means by which to evaluate the language given the current constraints of the project? Could you or another content strategist sit in on sessions as they are scheduled to provide recommendations?

We ended up using Grammarly to get the language down in reading level and to provide some recommendations on cleaning up the language before soft launch. Moving forward it would be great to work with you on refining for a more DIY use case.

**Comment by meganp-usds** [comment]
@celestemespinoza This is helpful context. I put a note in your Slack channel about us all syncing up at the end of next week. Louise and I plan to bring some concrete ideas to show you how we would make adjustments to improve the accessibility. From what I've seen, it's beyond the individual wording and more about information architecture, context, and format (e.g., can the wheel be a vertical layout with sections). Looking forward to collaborating next week and then figuring out where to go from there!

**Comment by AlexBornkesselUSDS** [comment]
This is still in progress (I could also see it being in progress for the 3 tools and Repo as part of the refinement process).

Also, @celestemespinoza I wasn't aware of this decision point: "We are not planning on launch or visibility to agency partners" for version 1 in top of 2024. My hope is we would launch v1 with broader sponsorship and support. Since we are already coordinating with OFCIO and OMB CX/Equity teams, it seems like we're already beyond USDS at this point. I also have a request from a fellow for us to share with USDC and am also getting connected with HRSA MCHB's Equity Lead as well.
